spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AYC0Vv7/Yk4hhyxZeo/hiQ3p7K/YthTuAnpeCqya2WzIKZ9pp5TQZBaiLzxt8bJ12AF/4tGvV0SxDyECR9LGI0RvAEaxXOWWSxI8ssAFyc+PNLnHoyxPSmD/ddVJ6rTA9otRDmv08AiBaDFUp2CcGTDvBaQjzgREcfuwRYj30gQQ5FCJotFxuaN9dys3c+EJIGFTIg/qgEECg7M0W3bmHfxkdjuUZ6g09TwxZeXCcGilBDc+N4q4T/G4dYsJ+W9WpiOtpdBrt7eANTiYLgOU9wq7raNbPuraOwJE5UafcBphkQyB3Visp/9kzf2DX97YsbtmV8p0DIUNnwbn0ePWuqmv0kPznHJerRWSaO1yUT1HjBBuS67SLo0/KLOOFAhzbspsrunrYZmPB/QQJsYRuQABEIeXZF8qni2aExoTPoyV9rG08LrBaSKqp0kZXUPfSzeHwOFuZUg7Rr3oIJBiCC8TBnKdviSqGxUYAYL02NqZVtTIdBEQz+NbA63v+MoENFLTEaT6fx2TmmWdfhHrDITcB6qzudQ6Ir8qmtsDJRm29Q=='
token:
  expiration_time: 86400000
  secret: '{cipher}AYBVDQquEkJMizvX7UXUJw5F1dXkdPj7ANzoiMNE6wYpk1plZasnMp18XgECgTlIfwUTVjgVDBdWZPJZuz1gshK1VCmW69NMkw4kSUb0axzU+mBRJu/sYgA5E9902m3xCR5vS13IWq2tzvBeOKB+f68A61uQwJNIe9OCFVAK+GysI5jM+5EwtVPbAlZT4EhdOq6jJ2c5+bJMDT0l+xqWU/sl//d+6CAJLZ9kMqkeWLqa7zWVhXN4HBiaeKHTZQVjCtPKxhSEycUlMsk+PkWWXIrugf92vHy/JMaEoj1dU8dPTfBcVJGHAMO0WVaJiswZGEmYlIejFbMwa4qV9netHTGe1dzeN/kxcjqay+iraLum1Kdl0JOsOuvWr+QT5r7rbWrilU1spwXN9dlGQCbMboeZaWl8WSwwUywEchgILPFyPoezdsTFxKZgzuM2w30JieMcGZ/UEMhN+NbLtwd/L3UC//y/yb5wmszz/dFwL7nGBOuYKQOnRAGzViXrp0RLEOz3yryRyWScJrgJcsLJW+L3FtMwWBlpfPDzkSA7Kkr9Cxk1bUPZyJoS5sPA2knSqz4='

gateway:
  ip: 172.18.0.5

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: There is no item
